FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir /home/raspi3b
RUN mkdir /home/raspi3b/boot3b

COPY ./src/raspi3b/image-raspi3b-resized-8G.img /home/raspi3b/
COPY ./src/raspi3b/qemu-6.2.0.tar.xz /home/raspi3b/
COPY ./src/raspi3b/boot3b/kernel8.img /home/raspi3b/boot3b/
COPY ./src/raspi3b/boot3b/bcm2710-rpi-3-b-plus.dtb /home/raspi3b/boot3b/

RUN apt-get update -y
RUN apt-get install xz-utils -y

WORKDIR /home/raspi3b
RUN tar -xvJf ./qemu-6.2.0.tar.xz

RUN apt-get install -y gcc make ninja-build pkg-config libglib2.0-dev
RUN apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev;
RUN apt-get install -y python libfdt-dev;
RUN apt-get install -y libgtk2.0-dev;
RUN apt-get update -y && apt-get upgrade -y;


WORKDIR /home/raspi3b/qemu-6.2.0
RUN mkdir build
WORKDIR /home/raspi3b/qemu-6.2.0/build

RUN ../configure --target-list=aarch64-softmmu,arm-softmmu
RUN make -j `nproc`


WORKDIR /home/raspi3b


