FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir /home/raspi4b
RUN mkdir /home/raspi4b/boot4b

COPY ./src/raspi4b-virtio/20230102_raspi_4_bullseye.img /home/raspi4b/
COPY ./src/raspi4b-virtio/qemu-6.2.0.tar.xz /home/raspi4b/
COPY ./src/raspi4b-virtio/boot4b/vmlinuz-6.0.0-6-arm64 /home/raspi4b/boot4b/
COPY ./src/raspi4b-virtio/boot4b/initrd.img-6.0.0-6-arm64 /home/raspi4b/boot4b/

RUN apt-get update -y
RUN apt-get install xz-utils -y

WORKDIR /home/raspi4b
RUN tar -xvJf ./qemu-6.2.0.tar.xz

RUN apt-get install -y gcc make ninja-build pkg-config libglib2.0-dev
RUN apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg8-dev libgif-dev;
RUN apt-get install -y python libfdt-dev;
RUN apt-get install -y libgtk2.0-dev;
RUN apt-get update -y && apt-get upgrade -y;

WORKDIR /home/raspi4b/qemu-6.2.0
RUN mkdir build
WORKDIR /home/raspi4b/qemu-6.2.0/build

RUN ../configure --target-list=aarch64-softmmu,arm-softmmu
RUN make -j `nproc`


WORKDIR /home/raspi4b


